Rails:
  Enabled: true

AllCops:
  # Exclude generated files
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
  TargetRubyVersion: 2.3

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Enabled: False
